### ISSUE TITLE
Frame vector initialization with memset

### ISSUE THREAD

**Issue by geromidg** [rock-core/base-types#118]
https://github.com/rock-core/base-types/blob/a24cde6444b41aa2b4308fe4205d1e67377e3c72/src/samples/Frame.cpp#L88-L96

Is there a particular reason to circumvent the standard library's functions for this allocation?

**Comment by doudou** [comment]
Sorry if I'm being pedantic, but this is not allocation but initialization.

At the time this has been written, `memset` was not part of the C++ standard. Now it is, so it's actually a standard library function ...

Now, what did you have in mind ?

**Comment by geromidg** [comment]
You are right, it's an initialization of course.

Wouldn't it be more readable to use an STL specific function, such as `std::fill()`?

**Comment by doudou** [comment]
I personally have no particular opinion one way or the other, to be honest. This is a type-pruned vector of bytes, so memset sounds as reasonable as fill to me.

**Comment by geromidg** [comment]
OK, that's understandable. Readability is a matter of opinion anyway.
