### ISSUE TITLE
base/Pose "Euler" vs "Tait-Bryan" angles

### ISSUE THREAD

**Issue by leifole** [rock-core/base-types#49]
In base/Pose.hpp our getEuler() method decomposes a base::Orientation into a sequence of rotations using 3 distinct axes (x,y,z). 
In that case, one usually speeks of "Tait-Bryan" angles, instead of (proper, classic) Euler angles.

Also, there is a convention (in Germany even a "DIN-NORM" to use a z,y',x'' sequence for yaw-pitch-roll. The documentation's naming scheme is a little bit confusing here, using a2, a1 and a0 names. 

see also http://de.wikipedia.org/wiki/Eulersche_Winkel#.E2.80.9Ez.2C_y.E2.80.B2.2C_x.E2.80.B3-Konvention.E2.80.9C_in_der_Fahrzeugtechnik

**Comment by goldhoorn** [comment]
What exactly do you suggest?

Did you have a look at: https://rock.opendfki.de/wiki/WikiStart/Standards
specially: http://www.ros.org/reps/rep-0103.html

?

**Comment by doudou** [comment]
@leifole: I would welcome all patches (documentation, naming of methods) aimed at making the Euler exact convention we're using. However, for convenience reasons, I would prefer keeping the getEuler naming around.

**Comment by leifole** [comment]
Ok, I will prepare a patch only altering the docu trying to clarify things.

Regards,
Leif

Am 08.06.2015 um 16:22 schrieb Sylvain Joyeux:

**Comment by jmachowinski** [comment]
I assume this one has been solved.
